# NOTE: update this with your service name
service: anomaly-refactor

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  #environment:
  #  SAMPLE_ENV_VAR: ${env:SAMPLE_ENV_VAR}

functions:
  hello:
    handler: src/endpoints/hello.handler
    events:
      - http:
          path: hello
          method: get
  calc:
    handler: src/endpoints/calc.handler
    events:
      - http:
          path: calc
          method: get
  reverse:
    handler: src/endpoints/reverse.handler
    events:
      - http:
          path: reverse
          method: post
